### ISSUE TITLE
Deploy to flathub.org

### ISSUE THREAD

**Issue by allanday** [flathub/linux-store-frontend#63]
I think it's time that the Linux Store Frontend replaced the existing site at flathub.org, even if it's not completely finished. The minimum requirements for deployment are probably:

- [x] Add a beta label - #62
- [x] Remove non-functional links - #61 
- [x] Simpler installation instructions - #52 
- [x] Move the repo off @jgarciao's namespace (maybe it should live under https://github.com/flathub/ ?)
- [x] Ensure that we have at least two people with access to the repo

**Comment by TingPing** [comment]
>  Move the repo off @jgarciao's namespace (maybe it should live under https://github.com/flathub/ ?)

Let me know what the repo names should be and I'll make them and set up permissions.

**Comment by jgarciao** [comment]
Although the frontend and backend are currently only used in Flathub I've developed them (specially the backend) in a way that could be used for other projects (for example a raspberry focused store)

That's why I would like to maintain the repo names. I can transfer the ownership to the Flathub organization if you agree

**Comment by allanday** [comment]
> Although the frontend and backend are currently only used in Flathub I've developed them (specially the backend) in a way that could be used for other projects (for example a raspberry focused store)
> 
> That's why I would like to maintain the repo names. I can transfer the ownership to the Flathub organization if you agree

That sounds fine to me. The main thing is that people can contribute, and it looks like a proper project.

**Comment by TingPing** [comment]
Both repos have been created, added to the website team, and @jgarciao added to the team as well.

**Comment by jgarciao** [comment]
According to this article the destination organization should not have any
repo with the same name

https://help.github.com/articles/about-repository-transfers/



El dc., 4 d’abr. 2018, 21:55, TingPing <notifications@github.com> va
escriure:

**Comment by TingPing** [comment]
Hmm, I didn't realize github had an actual transfer feature built in. Ok I'll delete them, temporarily give you repo creation permissions, and you can transfer it.

**Comment by jgarciao** [comment]
I've transferred the repos.

**Comment by jgarciao** [comment]
I think I've done all the remaining things. See demo at http://45.55.104.129/home

**Comment by allanday** [comment]
The site is looking good to me. The only thing I'd like to see is a more prominent beta label.

**Comment by allanday** [comment]
> The only thing I'd like to see is a more prominent beta label.

This is done now.

**Comment by TingPing** [comment]
I personally think #69 should be a blocker too (and be relatively easy to solve).
